# Generated by Django 4.2 on 2023-05-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerShop', '0002_alter_category_options_rename_first_name_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(null=True, related_name='product', to='FlowerShop.category'),
        ),
    ]
